BEGIN;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 1','MINION',2,2,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 2','MINION',3,4,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 3','MINION',4,3,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 4','MINION',5,5,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 5','MINION',6,7,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 6','MINION',1,1,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 7','MINION',2,2,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 8','MINION',3,4,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 9','MINION',4,3,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 10','MINION',5,5,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 11','MINION',6,7,9, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 12','MINION',1,1,1, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 13','MINION',2,2,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 14','MINION',3,4,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 15','MINION',4,3,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 16','MINION',5,5,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 17','MINION',6,7,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 18','MINION',1,1,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 19','MINION',2,2,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 20','MINION',3,4,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 21','MINION',4,3,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 22','MINION',5,5,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 23','MINION',6,7,9, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 24','MINION',1,1,1, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 25','MINION',2,2,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 26','MINION',3,4,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 27','MINION',4,3,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 28','MINION',5,5,5, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 29','MINION',6,7,7, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Minion 30','MINION',1,1,3, '{}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Firebolt','SPELL',1,NULL,NULL, '{"kind": "DAMAGE", "amount": 2}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Arcane Shot','SPELL',2,NULL,NULL, '{"kind": "DAMAGE", "amount": 4}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Healing Light','SPELL',2,NULL,NULL, '{"kind": "HEAL", "amount": 3}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Mind Spark','SPELL',3,NULL,NULL, '{"kind": "DRAW", "amount": 2}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Meteor','SPELL',5,NULL,NULL, '{"kind": "DAMAGE", "amount": 8}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Rejuvenate','SPELL',3,NULL,NULL, '{"kind": "HEAL", "amount": 6}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Zap','SPELL',1,NULL,NULL, '{"kind": "DAMAGE", "amount": 1}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Insight','SPELL',1,NULL,NULL, '{"kind": "DRAW", "amount": 1}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Blizzard','SPELL',4,NULL,NULL, '{"kind": "DAMAGE_ALL", "amount": 2}'::jsonb) ON CONFLICT (name) DO NOTHING;
INSERT INTO cards(name,type,cost,attack,health,effect_json) VALUES ('Drain','SPELL',3,NULL,NULL, '{"kind": "DRAIN", "amount": 3}'::jsonb) ON CONFLICT (name) DO NOTHING;
COMMIT;